/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.simplesearchtool;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author bernardoleal
 */
public class PasswordGeneratorUI extends javax.swing.JFrame {

    /**
     * Creates new form Editor
     */
    private int passwordLength;

    
    public PasswordGeneratorUI() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jTxtaPassword.setEditable(false);
    }
    
    private void generatePassword() {
        String lower = "qwertyuiopasdfghjklzxcvbnm";
        String upper = "QWERTYUIOPASDFGHJKLZXCVBNM";
        String numbers = "1234567890";
        String special = "!@#$%^&*()_+-=[]{}|;':,.<>?/";
        
        StringBuilder passChar = new StringBuilder();
        if (jcbLower.isSelected()) passChar.append(lower);
        if (jcbUpper.isSelected()) passChar.append(upper);
        if (jcbNumber.isSelected()) passChar.append(numbers);
        if (jcbSpecial.isSelected()) passChar.append(special);
        
        if (passChar.length() == 0) {
            JOptionPane.showMessageDialog(null, "Select at least one of the options", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        try{
            passwordLength = Integer.parseInt(jtxtSize.getText()); //convert string to integer
            if (passwordLength <= 0) throw new NumberFormatException(); // if smaller than 0 or equal to 0, throw exception for the user to retry
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Enter a valid positive number", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        StringBuilder password = new StringBuilder();
        Random random = new Random();
        for (int i = 0; i < passwordLength; i++) {
            int index = random.nextInt(passChar.length()); // passChar has all the possible characters so it generates a random index between 0 and passwordLength -1
            password.append(passChar.charAt(index)); //create the password
        }
        jTxtaPassword.setText(password.toString());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblSize = new javax.swing.JLabel();
        jtxtSize = new javax.swing.JTextField();
        jcbLower = new javax.swing.JCheckBox();
        jcbUpper = new javax.swing.JCheckBox();
        jcbNumber = new javax.swing.JCheckBox();
        jcbSpecial = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtaPassword = new javax.swing.JTextArea();
        jbtnGenerate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblSize.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jlblSize.setText("Size of the Password:");

        jcbLower.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jcbLower.setText("LowerCased Letters");
        jcbLower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLowerActionPerformed(evt);
            }
        });

        jcbUpper.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jcbUpper.setText("UpperCased Letters");

        jcbNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jcbNumber.setText("Numbers (0-9)");
        jcbNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNumberActionPerformed(evt);
            }
        });

        jcbSpecial.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jcbSpecial.setText("Special Characters");
        jcbSpecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSpecialActionPerformed(evt);
            }
        });

        jTxtaPassword.setColumns(20);
        jTxtaPassword.setRows(5);
        jTxtaPassword.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(jTxtaPassword);

        jbtnGenerate.setText("Generate");
        jbtnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbSpecial)
                            .addComponent(jcbNumber)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jcbLower, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbUpper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblSize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jbtnGenerate)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSize)
                    .addComponent(jtxtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcbLower)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbUpper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbSpecial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnGenerate)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jcbLower.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNumberActionPerformed

    private void jcbSpecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSpecialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSpecialActionPerformed

    private void jcbLowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLowerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbLowerActionPerformed

    private void jbtnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerateActionPerformed
        // TODO add your handling code here:
        generatePassword();
    }//GEN-LAST:event_jbtnGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordGeneratorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordGeneratorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordGeneratorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordGeneratorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordGeneratorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtaPassword;
    private javax.swing.JButton jbtnGenerate;
    private javax.swing.JCheckBox jcbLower;
    private javax.swing.JCheckBox jcbNumber;
    private javax.swing.JCheckBox jcbSpecial;
    private javax.swing.JCheckBox jcbUpper;
    private javax.swing.JLabel jlblSize;
    private javax.swing.JTextField jtxtSize;
    // End of variables declaration//GEN-END:variables
}
