/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.simplesearchtool;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author bernardoleal
 */
public class PasswordManager extends javax.swing.JFrame {

    /**
     * Creates new form FileBrowser
     */
    private String loggedInUser;
    
    public PasswordManager(String username) {
          initComponents();
          this.loggedInUser = username;
          jlblAccountName.setText(username);
          jtxtPass.setEditable(true);
          
    }
    
    public void loadAccounts(){
        try {
            String filePath = System.getProperty("user.home") + "/passwords_" + loggedInUser + ".txt"; // I used chat to understand what to do since without the user.home the file was in a unwritable directory
            File userFile = new File(filePath);
            if (userFile.exists()) {
                BufferedReader br = new BufferedReader(new FileReader(userFile));
                List<String> accounts = new ArrayList<>();
                String line;
                //line = br.readLine();
                while ((line = br.readLine()) != null) {
                    accounts.add(line);
                }
                br.close();
                jlstInfo.setListData(accounts.toArray(new String[0])); // also gpt here to be able to convert accounts into elements for the list
                
            }
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("problema no load");
        }
    }
    
    private void saveAccount(String accountName, String password) { //Users/bernardoleal/NetBeansProjects/PasswordManager/passwords_user1.txt
        try {
            String filePath = System.getProperty("user.home") + "/passwords_" + loggedInUser + ".txt";
            File userFile = new File(filePath);
            BufferedWriter bw = new BufferedWriter(new FileWriter(userFile, true));
            bw.write("Username: " + accountName + " | " + "Password:" + password);
            bw.newLine();
            bw.close();
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("problema no save");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnNewPass = new javax.swing.JButton();
        jlblTitle = new javax.swing.JLabel();
        jlblSubTitle = new javax.swing.JLabel();
        jBtnOut = new javax.swing.JButton();
        jLblUser = new javax.swing.JLabel();
        jlblPass = new javax.swing.JLabel();
        jBtnAdd = new javax.swing.JButton();
        jtxtPass = new javax.swing.JTextField();
        jTxtUser = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlstInfo = new javax.swing.JList<>();
        jlblAccountName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnNewPass.setText("Generate Password");
        jbtnNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNewPassActionPerformed(evt);
            }
        });

        jlblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jlblTitle.setText("Password Manager");

        jlblSubTitle.setText("Welcome back, ");

        jBtnOut.setText("Log Out");
        jBtnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOutActionPerformed(evt);
            }
        });

        jLblUser.setText("Username:");

        jlblPass.setText("Password:");

        jBtnAdd.setText("Add");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jlstInfo);

        jlblAccountName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jlblAccountName.setText("username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jlblTitle)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtUser, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtPass)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblPass)
                                    .addComponent(jLblUser))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblSubTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblAccountName)
                        .addGap(77, 77, 77)
                        .addComponent(jBtnOut)))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnNewPass)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblSubTitle)
                        .addComponent(jlblAccountName)))
                .addGap(18, 18, 18)
                .addComponent(jbtnNewPass)
                .addGap(18, 18, 18)
                .addComponent(jLblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jlblPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnAdd)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNewPassActionPerformed
//        // TODO add your handling code here:
        new PasswordGeneratorUI().setVisible(true);
       

    }//GEN-LAST:event_jbtnNewPassActionPerformed

    private void jBtnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOutActionPerformed
        // TODO add your handling code here:
        new LogInMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnOutActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        // TODO add your handling code here:
        String username = jTxtUser.getText();
        String password = jtxtPass.getText();
        
        if (!username.isEmpty() && !password.isEmpty()) {
            saveAccount(username, password);
            jTxtUser.setText("");
            jtxtPass.setText("");
            loadAccounts();
        } else {
            JOptionPane.showMessageDialog(null, "Enter both username and password", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        String userInfo = "Username: " + username + " | Password: " + password;
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (int i = 0; i < jlstInfo.getModel().getSize(); i++) {
            listModel.addElement(jlstInfo.getModel().getElementAt(i)); // add the info of the list into the new default list
        }
         listModel.addElement(userInfo);
    
        jlstInfo.setModel(listModel); 

   
    }//GEN-LAST:event_jBtnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordManager("test").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnOut;
    private javax.swing.JLabel jLblUser;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTxtUser;
    private javax.swing.JButton jbtnNewPass;
    private javax.swing.JLabel jlblAccountName;
    private javax.swing.JLabel jlblPass;
    private javax.swing.JLabel jlblSubTitle;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JList<String> jlstInfo;
    private javax.swing.JTextField jtxtPass;
    // End of variables declaration//GEN-END:variables
}
