/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.musiccomposer;

import java.util.List;
import javax.swing.JTextArea;



/**
 *
 * @author bernardoleal
 */
public class MainPage extends javax.swing.JFrame {

    private String loggedInUser;
    private Thread recordingThread;
    private MusicSingleton playerSingleton;
    //private JTextArea jTxtAChords;
    
    public MainPage(String username) {
        playerSingleton = MusicSingleton.getInstance();
        playerSingleton.setMainPage(this);
        initComponents();
        this.loggedInUser = username;
        jlblAccountName.setText(username);
    }
    
    public void updateTextArea(String text) {
    jTxtAChords.setText(text);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlblAccountName = new javax.swing.JLabel();
        jBtnOut = new javax.swing.JButton();
        jBtnCmaj = new javax.swing.JButton();
        jBtnCmin = new javax.swing.JButton();
        jBtnCdim = new javax.swing.JButton();
        jBtnCaug = new javax.swing.JButton();
        jBtnCsus2 = new javax.swing.JButton();
        jBtnCsus4 = new javax.swing.JButton();
        jBtnListen = new javax.swing.JButton();
        jTBtnRecord = new javax.swing.JToggleButton();
        jBtnTempo = new javax.swing.JButton();
        jBtnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAChords = new javax.swing.JTextArea();
        jRBtnPiano = new javax.swing.JRadioButton();
        jRBtnGuitar = new javax.swing.JRadioButton();
        jRBtnViolin = new javax.swing.JRadioButton();
        jRBtnFlute = new javax.swing.JRadioButton();
        jRBtnTrumpet = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Hiragino Mincho ProN", 2, 13)); // NOI18N
        jLabel1.setText("Welcome back,");

        jlblAccountName.setFont(new java.awt.Font("Hiragino Mincho ProN", 3, 14)); // NOI18N
        jlblAccountName.setText("username");

        jBtnOut.setText("Log Out");
        jBtnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOutActionPerformed(evt);
            }
        });

        jBtnCmaj.setText("Cmaj");
        jBtnCmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCmajActionPerformed(evt);
            }
        });

        jBtnCmin.setText("Cmin");
        jBtnCmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCminActionPerformed(evt);
            }
        });

        jBtnCdim.setText("Cdim");
        jBtnCdim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCdimActionPerformed(evt);
            }
        });

        jBtnCaug.setText("Caug");
        jBtnCaug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCaugActionPerformed(evt);
            }
        });

        jBtnCsus2.setText("Csus2");
        jBtnCsus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCsus2ActionPerformed(evt);
            }
        });

        jBtnCsus4.setText("Csus4");
        jBtnCsus4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCsus4ActionPerformed(evt);
            }
        });

        jBtnListen.setText("▶ Listen");
        jBtnListen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListenActionPerformed(evt);
            }
        });

        jTBtnRecord.setText("🎤 Record (ON/OFF)");
        jTBtnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBtnRecordActionPerformed(evt);
            }
        });

        jBtnTempo.setText("🎼 Tempo");
        jBtnTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTempoActionPerformed(evt);
            }
        });

        jBtnSave.setText("💾 Save");

        jLabel2.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        jLabel2.setText("Chord Player");

        jTxtAChords.setColumns(20);
        jTxtAChords.setRows(5);
        jScrollPane1.setViewportView(jTxtAChords);

        jRBtnPiano.setText("Piano");
        jRBtnPiano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnPianoActionPerformed(evt);
            }
        });

        jRBtnGuitar.setText("Guitar");
        jRBtnGuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnGuitarActionPerformed(evt);
            }
        });

        jRBtnViolin.setText("Violin");
        jRBtnViolin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnViolinActionPerformed(evt);
            }
        });

        jRBtnFlute.setText("Flute");
        jRBtnFlute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnFluteActionPerformed(evt);
            }
        });

        jRBtnTrumpet.setText("Trumpet");
        jRBtnTrumpet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBtnTrumpetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTBtnRecord)
                .addGap(44, 44, 44)
                .addComponent(jBtnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnListen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jBtnCmaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCdim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCaug)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCsus2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCsus4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnOut)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBtnPiano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBtnGuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBtnViolin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBtnFlute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBtnTrumpet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnTempo)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlblAccountName)
                    .addComponent(jBtnOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCmaj)
                    .addComponent(jBtnCmin)
                    .addComponent(jBtnCdim)
                    .addComponent(jBtnCaug)
                    .addComponent(jBtnCsus2)
                    .addComponent(jBtnCsus4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTBtnRecord)
                    .addComponent(jBtnSave)
                    .addComponent(jBtnListen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnTempo)
                        .addComponent(jRBtnViolin)
                        .addComponent(jRBtnFlute)
                        .addComponent(jRBtnTrumpet))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRBtnPiano)
                        .addComponent(jRBtnGuitar)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOutActionPerformed
        // TODO add your handling code here:
        new LogInMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnOutActionPerformed

    private void jBtnListenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListenActionPerformed
       playerSingleton.playRecordedChords();
    }//GEN-LAST:event_jBtnListenActionPerformed

    private void jBtnCmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCmajActionPerformed
        playerSingleton.playChord("Cmaj");
    }//GEN-LAST:event_jBtnCmajActionPerformed

    private void jBtnCminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCminActionPerformed
        playerSingleton.playChord("Cmin");
    }//GEN-LAST:event_jBtnCminActionPerformed

    private void jBtnCdimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCdimActionPerformed
        playerSingleton.playChord("Cdim");
    }//GEN-LAST:event_jBtnCdimActionPerformed

    private void jBtnCaugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCaugActionPerformed
        playerSingleton.playChord("Caug");
    }//GEN-LAST:event_jBtnCaugActionPerformed

    private void jBtnCsus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCsus2ActionPerformed
        playerSingleton.playChord("Csus2");
    }//GEN-LAST:event_jBtnCsus2ActionPerformed

    private void jBtnCsus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCsus4ActionPerformed
       playerSingleton.playChord("Csus4");
    }//GEN-LAST:event_jBtnCsus4ActionPerformed

    private void jTBtnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBtnRecordActionPerformed
       playerSingleton.startRecording();
    }//GEN-LAST:event_jTBtnRecordActionPerformed

    private void jBtnTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTempoActionPerformed
        playerSingleton.setTempo(120);
    }//GEN-LAST:event_jBtnTempoActionPerformed

    private void jRBtnPianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnPianoActionPerformed
        playerSingleton.setInstrument("Piano");
    }//GEN-LAST:event_jRBtnPianoActionPerformed

    private void jRBtnGuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnGuitarActionPerformed
        playerSingleton.setInstrument("Guitar");
    }//GEN-LAST:event_jRBtnGuitarActionPerformed

    private void jRBtnViolinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnViolinActionPerformed
       playerSingleton.setInstrument("Violin");
    }//GEN-LAST:event_jRBtnViolinActionPerformed

    private void jRBtnFluteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnFluteActionPerformed
        playerSingleton.setInstrument("Flute");
    }//GEN-LAST:event_jRBtnFluteActionPerformed

    private void jRBtnTrumpetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBtnTrumpetActionPerformed
        playerSingleton.setInstrument("Trumpet");
    }//GEN-LAST:event_jRBtnTrumpetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage("test").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCaug;
    private javax.swing.JButton jBtnCdim;
    private javax.swing.JButton jBtnCmaj;
    private javax.swing.JButton jBtnCmin;
    private javax.swing.JButton jBtnCsus2;
    private javax.swing.JButton jBtnCsus4;
    private javax.swing.JButton jBtnListen;
    private javax.swing.JButton jBtnOut;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jBtnTempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRBtnFlute;
    private javax.swing.JRadioButton jRBtnGuitar;
    private javax.swing.JRadioButton jRBtnPiano;
    private javax.swing.JRadioButton jRBtnTrumpet;
    private javax.swing.JRadioButton jRBtnViolin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToggleButton jTBtnRecord;
    private javax.swing.JTextArea jTxtAChords;
    private javax.swing.JLabel jlblAccountName;
    // End of variables declaration//GEN-END:variables
}
